# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a02948e697dfb2c8330a281752c699c2974c533dc315f4172fb5299484c9a3b103425f7e2b3d2a85e67fe15ad2c2590304a3bcdb0c0f4416d93a93c29f8da21

test:
  secret_key_base: 16ed818ad298527cfe1301086cae840fef6968305191d01a5c2c8ba75a6caef94b8d50ce6a9d1cebe2558db85487bc66973e41945c7d641a6ad37a3520489cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
